data:
  dataset: "celeba"
  root: /data_new/manu/celebA/data/celeba-subset/200k
  from_hub: false  # run "python download_dataset.py --output_dir YOUR_PATH" first if you want to use false here
  repo_name: "electronickale/cmu-10799-celeba64-subset"
  use_vae: false        # if true, load precomputed latents; else load raw images
  image_size: 128         # pixel resolution (used for raw images or VAE decode output)
  latent_size: 8         # spatial size of VAE latents (64 / 8 = 8)
  channels: 3            # latent channels when use_vae=true, else 3
  num_workers: 8
  pin_memory: true
  augment: true

# Model architecture:
#   - set model.type: "dit" to train Flow Matching with Diffusion Transformer
#   - set model.type: "unet" to use the original U-Net
model:
  type: dit #"dit"

  # DiT options:
  # Option A) preset variant from facebookresearch/DiT naming:
  dit_variant: "DiT-S/8" #null, DiT-S/1
  mlp_ratio: 4.0
  learn_sigma: false

  # Option B) custom DiT size (used if dit_variant is not set):
  patch_size: 4
  hidden_size: 384
  depth: 12
  num_heads: 6

  # U-Net options (used only when type == "unet"):
  # NOTE: base_channels reduced from 128 -> 80 to target ~30M params (from ~80M)
  base_channels: 80
  channel_mult: [1, 2, 2, 4]
  num_res_blocks: 2
  attention_resolutions: [16]
  num_heads: 4
  dropout: 0.1
  use_scale_shift_norm: true

# Training hyperparameters (same as Flow Matching for fair comparison)
training:
  batch_size: 32
  gradient_accumulation_steps: 4
  const_lr: false ##### unet
  learning_rate: 1.0e-4
  warmup_steps: 10000
  peak_lr: 1.0e-4
  min_lr: 1.0e-6
  weight_decay: 0.01
  betas: [0.9, 0.999]
  ema_decay: 0.999
  ema_start: 1000
  gradient_clip_norm: 1.0
  num_iterations: 300000 ## dit
  log_every: 1
  sample_every: 10000
  save_every: 50000
  num_samples: 64

# Flow matching specific parameters
flow_matching:
  num_inference_steps: 50  # Number of Euler integration steps during sampling
  sigma_min: 0.0  # Minimum noise level (0.0 for deterministic flow)

sampling:
  num_steps: 50  # Number of sampling steps (matches num_inference_steps)
  sampler: "flow_matching"

infrastructure:
  seed: 42
  device: "cuda"
  num_gpus: 1 # 1 should be ok
  mixed_precision: true # both true and false should work
  compile_model: false # only tested false

checkpoint:
  dir: "/data_new/manu/celebA/checkpoints"
  resume: null

logging:
  dir: "/data_new/manu/celebA/logs"
  wandb:
    enabled: true
    project: "cmu-10799-diffusion"
    entity: null
